# Generated by Django 5.2.4 on 2025-09-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dslr', 'DSLR Camera'), ('mirrorless', 'Mirrorless camera'), ('lens', 'Lens'), ('lighting', 'Lighting Equipment'), ('tripod', 'Trippod & Support'), ('audio', 'Audio Equipment'), ('accessory', 'Accessory')], max_length=50)),
                ('brand', models.CharField(choices=[('canon', 'Canon'), ('nikon', 'Nikon'), ('sony', 'Sony'), ('panasonic', 'Panasonic'), ('sigma', 'Sigma'), ('fujifilm', 'Fujifilm'), ('tamron', 'Tamron'), ('other', 'Other')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent - Like new'), ('very-good', 'Very Good - Minor signs of use'), ('good', 'Good - Normal waer and tear')], max_length=50)),
                ('description', models.TextField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('pickup', models.BooleanField(default=True)),
                ('shipping', models.BooleanField(default=False)),
                ('meetup', models.BooleanField(default=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentitapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentitapp.product')),
            ],
        ),
    ]
