# Generated by Django 5.2.4 on 2025-09-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0002_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
