# Generated by Django 5.2.4 on 2025-10-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0006_productfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='signup',
        ),
    ]
