# Generated by Django 5.2.4 on 2025-10-09 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0007_remove_product_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='signup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentitapp.signup'),
            preserve_default=False,
        ),
    ]
