# Generated by Django 5.2.4 on 2025-10-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0010_alter_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Currently Unavailable')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
