# Generated by Django 5.2.4 on 2025-10-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0012_lendermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentitapp.login')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentitapp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='LenderMessage',
        ),
    ]
