# Generated by Django 5.2.4 on 2025-10-14 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0013_rentermessage_delete_lendermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentermessage',
            name='signup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentitapp.signup'),
            preserve_default=False,
        ),
    ]
