# Generated by Django 5.2.4 on 2025-10-15 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0014_rentermessage_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
