# Generated by Django 5.2.4 on 2025-10-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0016_rentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('thiruvananthapuram', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('pathanamthitta', 'Pathanamthitta'), ('alappuzha', 'Alappuzha'), ('kottayam', 'Kottayam'), ('idukki', 'Idukki'), ('ernamkulam', 'Ernamkulam'), ('trissur', 'Trissur'), ('palakkad', 'Palakkad'), ('malappuram', 'Malappuram'), ('kozhikkode', 'Kozhikkode'), ('wayanad', 'Wayanad'), ('kannur', 'Kannur'), ('kasaragode', 'Kasaragode')], max_length=100),
        ),
    ]
