# Generated by Django 5.2.4 on 2025-10-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0017_alter_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrequest',
            name='rental_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
