# Generated by Django 5.2.4 on 2025-10-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0018_rentrequest_rental_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='p_image',
            field=models.ImageField(default='profile_images/default-user.png', upload_to='profile_images/'),
        ),
    ]
