# Generated by Django 5.2.4 on 2025-10-20 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0019_signup_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrequest',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
