# Generated by Django 5.2.4 on 2025-10-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0021_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrequest',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
