# Generated by Django 5.2.4 on 2025-10-31 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0022_rentrequest_final_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rent_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentitapp.rentrequest')),
            ],
        ),
    ]
