# Generated by Django 5.2.4 on 2025-08-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0005_order_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pincode',
            new_name='postal_code',
        ),
    ]
