# Generated by Django 5.2.4 on 2025-08-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0006_rename_pincode_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('card', 'Debit/Credit Card'), ('netbanking', 'UPI/Net Banking'), ('banktransfer', 'Bank Transfer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('purchase', 'purchase'), ('purchased', 'Continue Purchase')], default='purchase', max_length=20),
        ),
    ]
