# Generated by Django 5.2.4 on 2025-08-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0008_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.CharField(choices=[('card', 'Debit/Credit Card'), ('netbanking', 'UPI/Net Banking'), ('banktransfer', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('purchase', 'purchase'), ('purchased', 'Continue Purchase')], default='purchase', max_length=20)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtHome.cart')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtHome.login')),
            ],
        ),
    ]
