# Generated by Django 5.2.4 on 2025-08-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0011_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('purchase', 'purchase'), ('purchased', 'Place Order')], default='purchase', max_length=20),
        ),
    ]
