# Generated by Django 5.2.4 on 2025-08-08 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0012_remove_order_cart_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArtHome.product'),
            preserve_default=False,
        ),
    ]
