# Generated by Django 5.2.4 on 2025-08-08 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0014_alter_order_login_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtHome.login'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtHome.product'),
        ),
    ]
