# Generated by Django 5.2.4 on 2025-08-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0015_alter_order_login_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
