# Generated by Django 5.2.4 on 2025-08-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0016_remove_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtHome.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtHome.product')),
            ],
        ),
    ]
