# Generated by Django 5.2.4 on 2025-08-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0018_order_product_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bio',
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='purchase', max_length=20),
        ),
    ]
