# Generated by Django 5.2.4 on 2025-08-21 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0019_seller_bio_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='m_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='ArtHome.product'),
        ),
    ]
