# Generated by Django 5.2.4 on 2025-08-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0020_remove_product_m_date_alter_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_list',
        ),
    ]
