# Generated by Django 5.2.4 on 2025-08-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0022_rename_payment_order_payment_method_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Initiated', 'Initiated'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
