# Generated by Django 5.2.4 on 2025-09-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0023_remove_order_status_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_amount',
            new_name='amount',
        ),
    ]
