# Generated by Django 5.2.4 on 2025-09-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0024_rename_total_amount_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Debit/Credit Card'), ('netbanking', 'UPI/Net Banking'), ('banktransfer', 'Bank Transfer')], default='card', max_length=20),
        ),
    ]
