# Generated by Django 5.2.4 on 2025-09-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0025_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
