# Generated by Django 5.2.4 on 2025-09-18 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtHome', '0028_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='ArtHome.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ArtHome.product'),
        ),
    ]
